modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "armor_model_api"
version = "${version}"
displayName = "Armor Model API"
authors = "Daedelus"
iconFile = "assets/armor_model_api/icon.png"
description = '''
Renders Bedrock/GeckoLib geo armor models through the vanilla armor pipeline.
'''

[[dependencies.armor_model_api]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armor_model_api]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_min_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "armor_model_api.mixins.json"
