modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "armor_model_api"
version = "${version}"
displayName = "Armor Model API"
authors = "ZsoltMolnarrr"
description = '''
Renders armor with custom geometry authored in the Bedrock/GeckoLib geo format, through the vanilla armor rendering pipeline.
'''

[[dependencies.armor_model_api]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armor_model_api]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "armor_model_api.mixins.json"
